import turtle
sqrt3 = 3**0.5
leo = turtle.Turtle()
leo.color("blue")
leo.shape("arrow")
mikey = turtle.Turtle()
mikey.color("orange")
mikey.shape("circle")
don = turtle.Turtle()
don.color("purple")
don.shape("square")
raph = turtle.Turtle()
raph.color("red")
raph.shape("turtle")
leo.forward(50*sqrt3)
mikey.setpos(-50*sqrt3,0)
don.circle(50)
leo.left(120)
leo.forward(100*sqrt3)
mikey.setpos(0,150)
raph.left(90)
raph.forward(150)
